info:
  name: List Settings
  type: http
  seq: 1

http:
  method: GET
  url: "{{BASE_URL}}/api/v1/jhe_settings"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
