repos:
  # autoformat and lint Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff-check
        types_or:
          - python
          - jupyter
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or:
          - python
          - jupyter
        exclude: '(^|.*/)(migrations|data)/'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
