repos:
  # autoformat and lint Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0671d8ab202c4ac093b78433ae5baf74f3fc7246  # frozen: v0.15.15
    hooks:
      - id: ruff-check
        types_or:
          - python
          - jupyter
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or:
          - python
          - jupyter
        exclude: '(^|.*/)(migrations|data)/'

  # github actions security checks
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9  # frozen: v1.25.2
    hooks:
      - id: zizmor
        args:
          - --fix=all

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
