# Generated by Django 6.0.3 on 2026-04-04 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_practitioner_birth_date_alter_datasource_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='core.patient')),
            ],
            options={
                'unique_together': {('patient', 'system')},
            },
        ),
    ]
