# Generated by Django 6.0.3 on 2026-04-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_practitioner_birth_date_alter_datasource_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientWearableConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('ow_user_id', models.CharField(max_length=255)),
                ('consented_scopes', models.JSONField(default=list)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_connections', to='core.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'provider'), name='core_patientwearableconnection_unique_patient_provider')],
            },
        ),
    ]
