# Generated by Django 6.0.3 on 2026-04-07 22:23
#
# Data migration: copies PatientExternalId(system='open-wearables').external_id
# into JheUser.identifier with an "ow:" prefix BEFORE dropping the table.
# Anyone running an earlier version of this branch with PatientExternalId rows
# will have their OW user ID mappings preserved on JheUser.identifier so the
# next call to wearable_redirect re-uses the existing OW user instead of
# silently creating a new one.

from django.db import migrations


def copy_external_ids_to_jhe_user(apps, schema_editor):
    """Copy PatientExternalId rows to JheUser.identifier as 'ow:<uuid>'."""
    PatientExternalId = apps.get_model("core", "PatientExternalId")
    JheUser = apps.get_model("core", "JheUser")

    for ext in PatientExternalId.objects.filter(system="open-wearables").select_related(
        "patient__jhe_user"
    ):
        jhe_user = ext.patient.jhe_user
        if jhe_user is None:
            continue
        # Don't overwrite if a non-OW identifier was already set; only fill
        # in when the field is blank or already an OW identifier.
        if not jhe_user.identifier or jhe_user.identifier.startswith("ow:"):
            jhe_user.identifier = f"ow:{ext.external_id}"
            jhe_user.save(update_fields=["identifier"])


def reverse_copy_external_ids(apps, schema_editor):
    """Reverse migration: rebuild PatientExternalId rows from JheUser.identifier.

    Only restores rows whose JheUser still has an "ow:" identifier — we have
    no way to recover the original PatientExternalId.id values.
    """
    PatientExternalId = apps.get_model("core", "PatientExternalId")
    JheUser = apps.get_model("core", "JheUser")
    Patient = apps.get_model("core", "Patient")

    for jhe_user in JheUser.objects.filter(identifier__startswith="ow:"):
        try:
            patient = Patient.objects.get(jhe_user=jhe_user)
        except Patient.DoesNotExist:
            continue
        ow_user_id = jhe_user.identifier[3:]
        PatientExternalId.objects.update_or_create(
            patient=patient,
            system="open-wearables",
            defaults={"external_id": ow_user_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_patientexternalid'),
    ]

    operations = [
        migrations.RunPython(
            copy_external_ids_to_jhe_user,
            reverse_code=reverse_copy_external_ids,
        ),
        migrations.DeleteModel(
            name='PatientExternalId',
        ),
    ]
