# Generated by Django 6.0.3 on 2026-04-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_patientexternalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='provider_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
