# Generated by Django 6.0.4 on 2026-04-10 01:06

import django.db.models.deletion
from django.db import migrations, models


def create_ow_poller_system_user(apps, schema_editor):
    """Create the system user that the polling pipeline uses to call
    Observation.fhir_create(). is_superuser=True so the authz check at
    core/models.py:1188 takes the bypass branch; is_active=True because
    the account has no usable_password and Django auth backends will
    refuse a login regardless. Plan-time decision #3.
    """
    JheUser = apps.get_model("core", "JheUser")
    JheUser.objects.get_or_create(
        email="ow_poller@system.local",
        defaults={
            "is_superuser": True,
            "is_active": True,
            "is_staff": False,
        },
    )


def remove_ow_poller_system_user(apps, schema_editor):
    JheUser = apps.get_model("core", "JheUser")
    JheUser.objects.filter(email="ow_poller@system.local").delete()


# CodeableConcepts the polling pipeline needs that aren't seeded by the
# original JHE seed. omh-shim's 6 v0.1 data types map to these omh:* codes;
# Observation.fhir_create() looks them up by (coding_system, coding_code).
_NEW_CODEABLE_CONCEPTS = [
    ("https://w3id.org/openmhealth", "omh:heart-rate-variability:1.0", "Heart Rate Variability"),
    ("https://w3id.org/openmhealth", "omh:sleep-duration:2.0", "Sleep Duration"),
    ("https://w3id.org/openmhealth", "omh:physical-activity:1.2", "Physical Activity"),
]


def seed_polling_codeable_concepts(apps, schema_editor):
    CodeableConcept = apps.get_model("core", "CodeableConcept")
    for system, code, text in _NEW_CODEABLE_CONCEPTS:
        CodeableConcept.objects.get_or_create(
            coding_system=system,
            coding_code=code,
            defaults={"text": text},
        )


def remove_polling_codeable_concepts(apps, schema_editor):
    CodeableConcept = apps.get_model("core", "CodeableConcept")
    for system, code, _text in _NEW_CODEABLE_CONCEPTS:
        CodeableConcept.objects.filter(coding_system=system, coding_code=code).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_datasource_provider_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OWPollEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('cron', 'cron'), ('webhook', 'webhook'), ('manual', 'manual')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('completed', 'completed'), ('errored', 'errored')], default='started', max_length=16)),
                ('records_ingested', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-started_at'], name='core_owpoll_patient_4407a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='OWPollStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('heart_rate', 'heart_rate'), ('heart_rate_variability', 'heart_rate_variability'), ('step_count', 'step_count'), ('sleep_duration', 'sleep_duration'), ('sleep_episode', 'sleep_episode'), ('physical_activity', 'physical_activity')], max_length=32)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('backfill_complete', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient'], name='core_owpoll_patient_c2b9f3_idx')],
                'unique_together': {('patient', 'data_type')},
            },
        ),
        migrations.RunPython(create_ow_poller_system_user, remove_ow_poller_system_user),
        migrations.RunPython(seed_polling_codeable_concepts, remove_polling_codeable_concepts),
    ]
