# Generated by Django 6.0.4 on 2026-04-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_canonical_step_count_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='owpollstatus',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
