# Generated by Django 5.2.14 on 2026-05-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_patientidentifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='identifier',
        ),
        migrations.AddField(
            model_name='patient',
            name='aux_data',
            field=models.JSONField(null=True),
        ),
    ]
