# Generated by Django 6.0.4 on 2026-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_owpollstatus_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owpollstatus',
            name='data_type',
            field=models.CharField(choices=[('heart_rate', 'heart_rate'), ('heart_rate_variability', 'heart_rate_variability'), ('oxygen_saturation', 'oxygen_saturation'), ('step_count', 'step_count'), ('sleep_duration', 'sleep_duration'), ('sleep_episode', 'sleep_episode'), ('physical_activity', 'physical_activity')], max_length=32),
        ),
    ]
