# Generated by Django 5.2.14 on 2026-05-31 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_observation_aux_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='observationidentifier',
            name='core_observation_identifier_unique_observation_system_value',
        ),
        migrations.AlterUniqueTogether(
            name='practitionerorganization',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcesupportedscope',
            name='scope_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.codeableconcept'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='codeable_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.codeableconcept'),
        ),
        migrations.AlterField(
            model_name='observationidentifier',
            name='system',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationidentifier',
            name='value',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studypatientscopeconsent',
            name='scope_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.codeableconcept'),
        ),
        migrations.AlterField(
            model_name='studyscoperequest',
            name='scope_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.codeableconcept'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['subject_patient', '-last_updated'], name='core_observ_subject_4a622b_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasourcesupportedscope',
            constraint=models.UniqueConstraint(fields=('data_source', 'scope_code'), name='core_datasourcesupportedscope_unique_data_source_id_scope_code_id'),
        ),
        migrations.AddConstraint(
            model_name='observationidentifier',
            constraint=models.UniqueConstraint(fields=('system', 'value'), name='core_observationidentifier_unique_system_value'),
        ),
        migrations.AddConstraint(
            model_name='practitionerorganization',
            constraint=models.UniqueConstraint(fields=('practitioner', 'organization'), name='core_practitionerorganization_unique_practitioner_id_organization_id'),
        ),
        migrations.AddConstraint(
            model_name='studydatasource',
            constraint=models.UniqueConstraint(fields=('study', 'data_source'), name='core_studydatasource_unique_study_id_data_source_id'),
        ),
    ]
