# Generated by Django 5.2.14 on 2026-06-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_backfill_jhe_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jheclient',
            name='invitation_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jhesetting',
            name='value_type',
            field=models.TextField(choices=[('string', 'string'), ('int', 'int'), ('bool', 'bool'), ('float', 'float'), ('json', 'json')]),
        ),
        migrations.AlterField(
            model_name='jheuser',
            name='user_type',
            field=models.TextField(blank=True, choices=[('patient', 'Patient'), ('practitioner', 'Practitioner')], null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ow_key',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientinvitation',
            name='status',
            field=models.TextField(choices=[('issued', 'Issued'), ('reissued', 'Reissued'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')]),
        ),
        migrations.AlterField(
            model_name='practitionerorganization',
            name='role',
            field=models.TextField(choices=[('member', 'Member'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='member'),
        ),
    ]
