# Generated by Django 5.2.14 on 2026-06-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_jhesetting_setting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FhirAuxResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Condition', 'Condition'), ('QuestionnaireResponse', 'QuestionnaireResponse')])),
                ('patient_fhir_id', models.CharField(blank=True, null=True)),
                ('fhir_resource_id', models.CharField()),
                ('fhir_data', models.JSONField(null=True)),
                ('source', models.CharField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['resource_type', 'patient'], name='core_fhirau_resourc_59f1af_idx')],
            },
        ),
    ]
