# Generated by Django 5.2.14 on 2026-06-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_practitioner_drop_phone_add_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhirauxresource',
            name='resource_type',
            field=models.CharField(choices=[('AllergyIntolerance', 'AllergyIntolerance'), ('CarePlan', 'CarePlan'), ('CareTeam', 'CareTeam'), ('Condition', 'Condition'), ('Coverage', 'Coverage'), ('DiagnosticReport', 'DiagnosticReport'), ('DocumentReference', 'DocumentReference'), ('Encounter', 'Encounter'), ('FamilyMemberHistory', 'FamilyMemberHistory'), ('Goal', 'Goal'), ('Immunization', 'Immunization'), ('Location', 'Location'), ('Medication', 'Medication'), ('MedicationDispense', 'MedicationDispense'), ('MedicationRequest', 'MedicationRequest'), ('Procedure', 'Procedure'), ('Provenance', 'Provenance'), ('QuestionnaireResponse', 'QuestionnaireResponse'), ('RelatedPerson', 'RelatedPerson'), ('ServiceRequest', 'ServiceRequest'), ('Specimen', 'Specimen')]),
        ),
    ]
