# Generated by Django 5.2.14 on 2026-06-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_fhir_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fhirauxresource',
            name='core_fhirau_resourc_59f1af_idx',
        ),
        migrations.RemoveField(
            model_name='fhirauxresource',
            name='patient',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('medical_device', 'Medical Device'), ('personal_device', 'Personal Device'), ('patient_app', 'Patient App')], default='personal_device'),
        ),
        migrations.AddIndex(
            model_name='fhirauxresource',
            index=models.Index(fields=['resource_type', 'fhir_source'], name='core_fhirau_resourc_5fad9e_idx'),
        ),
    ]
