# Generated by Django 5.2.14 on 2026-06-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_fhirauxresource_core_fhirau_resourc_59f1af_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhirsource',
            name='fhir_base_url',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fhirsource',
            name='label',
            field=models.CharField(blank=True, default=''),
        ),
    ]
