# Generated by Django 5.2.14 on 2026-06-16 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_fhirsource_fhir_base_url_and_more'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default='')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_client', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.practitioner')),
            ],
        ),
    ]
