# Generated by Django 5.2.14 on 2026-06-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_practitionerclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datasource'),
        ),
    ]
