# Generated by Django 5.2.14 on 2026-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_observation_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirauxresource',
            name='ref_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
