# Generated by Django 5.2.14 on 2026-07-19 00:58

from django.db import migrations, models

from core.fhir.effective_time_frame import extract_effective_time_frame


def backfill_effective_time_frame(apps, schema_editor):
    # Populate the new columns from each existing Observation's omh_data blob, in batches, via
    # bulk_update so the historical model's plain save() (no custom sync) isn't required and
    # schema validation on legacy rows isn't re-triggered.
    Observation = apps.get_model("core", "Observation")
    batch = []
    for observation in Observation.objects.all().iterator():
        dt, start, end = extract_effective_time_frame(observation.omh_data or {})
        observation.effective_date_time = dt
        observation.effective_period_start = start
        observation.effective_period_end = end
        batch.append(observation)
        if len(batch) >= 1000:
            Observation.objects.bulk_update(
                batch, ["effective_date_time", "effective_period_start", "effective_period_end"]
            )
            batch = []
    if batch:
        Observation.objects.bulk_update(
            batch, ["effective_date_time", "effective_period_start", "effective_period_end"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fhirauxresource_ref_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='effective_date_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='effective_period_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='effective_period_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_effective_time_frame, migrations.RunPython.noop),
    ]
