# Generated by Django 5.2.14 on 2026-07-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fhirauxresource_ref_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EhrBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('vendor', models.CharField(default='epic')),
                ('fhir_base_url', models.TextField(unique=True)),
                ('fhir_version', models.CharField(blank=True, null=True)),
                ('npi', models.CharField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EhrBrandLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address_text', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.ehrbrand')),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='core_ehrbra_state_17e63c_idx'), models.Index(fields=['postal_code'], name='core_ehrbra_postal__0b73ca_idx'), models.Index(fields=['name'], name='core_ehrbra_name_330fc5_idx')],
            },
        ),
    ]
