# Generated by Django 5.1.7 on 2025-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_observation_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='icon_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
