# Generated by Django 5.2 on 2025-05-03 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_study_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='jhe_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhe_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='PractitionerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practitioner')),
            ],
        ),
    ]
