# Generated by Django 5.2 on 2025-05-10 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_jheuserorganization_core_jheuserorganization_unique_jhe_user_id_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jheuser',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.AddField(
            model_name='jheuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('practitioner', 'Practitioner')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patientorganization',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.DeleteModel(
            name='JheUserOrganization',
        ),
    ]
