# Generated by Django 5.2 on 2025-05-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jheuser_organizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='organizations',
            field=models.ManyToManyField(related_name='patients', through='core.PatientOrganization', to='core.organization'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='organizations',
            field=models.ManyToManyField(related_name='practitioners', through='core.PractitionerOrganization', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='patientorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='patientorganization',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='practitionerorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_links', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='practitionerorganization',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='core.practitioner'),
        ),
    ]
