# Generated by Django 5.2 on 2025-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patient_organizations_practitioner_organizations_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patientorganization',
            constraint=models.UniqueConstraint(fields=('patient_id', 'organization_id'), name='core_patientorganization_unique_patient_id_organization_id'),
        ),
    ]
