# Generated by Django 5.2 on 2025-05-26 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_patientorganization_core_patientorganization_unique_patient_id_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('jhe_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_collaborations', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='core.study')),
            ],
            options={
                'indexes': [models.Index(fields=['study', 'jhe_user'], name='studycollab_study_user_idx')],
                'unique_together': {('study', 'jhe_user')},
            },
        ),
    ]
