# Generated by Django 5.2 on 2025-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_patientorganization_core_patientorganization_unique_patient_id_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerorganization',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], default='member', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='practitionerorganization',
            unique_together={('practitioner', 'organization')},
        ),
    ]
