# Generated by Django 5.2 on 2025-06-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_practitionerorganization_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitionerorganization',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='member', max_length=10),
        ),
    ]
