# Generated by Django 5.2 on 2025-06-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_practitionerorganization_role'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS core_jheuser_groups;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS core_jheuser_user_permissions;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
