# https://docs.github.com/en/actions/writing-workflows/quickstart
name: Django Backend Test
run-name: Triggered by ${{ github.event_name }} to ${{ github.ref }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  run-full-test-suite:
    permissions:
      id-token: write

    name: Run full test suite
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_jhe_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:

      REGISTRATION_INVITE_CODE: "jhe"
      SITE_URL: "http://localhost:8000"
      DB_NAME: "test_jhe_dev"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "localhost"
      DB_PORT: "5432"
      OIDC_RSA_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\\Abc123\\n-----END RSA PRIVATE KEY-----"
      SECRET_KEY: "super-secret-key"

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - run: echo "Repository cloned successfully."

      - name: Set up Python for Django tests
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.11

      - name: Install dependencies using Pipenv
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run Django tests
        run: |
          pipenv run pytest -vx tests/

      - name: install coverage.py
        # needed for codecov
        run: |
          pip install coverage

      - name: upload coverage
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          use_oidc: true
